### ISSUE TITLE
About Flow and Combo files

### ISSUE THREAD

**Issue by mfurkanns** [msracver/Deep-Exemplar-based-Colorization#20]
I have two questions. I would be glad if you answer.

(1) Could you please explain what exactly are flow and combo files. What do they contain ?
(2) I got 
Check failed: status == CUDNN_STATUS_SUCCESS (4 vs. 0)  CUDNN_STATUS_INTERNAL_ERROR
What might be the reason of this error ?

python = 3.6.7
pytorch = 1.0.0 (cuda 8, cudnn 5.1)
torchvision = 0.2.1

Thank you so much.

**Comment by hmmlillian** [comment]
@mfurkanns I think your questions are very similar to 
https://github.com/msracver/Deep-Exemplar-based-Colorization/issues/3 
https://github.com/msracver/Deep-Exemplar-based-Colorization/issues/15
I hope those answers are helpful.

**Comment by mfurkanns** [comment]
Thank you for answers. 
I did everything you said below but it is still not working. I can build all projects.

1 - Edit "CommonSettings.props.example" (under similarity_subnet/windows/) to make the cuda version and cudnn path (if used) in it match yours, and save it as "CommonSettings.props" .

2 - Open solution Caffe (under similarity_subnet/windows/) and add deep_image_analogy (under similarity_subnet/windows/deep_image_analogy/) project.

3 - Build Caffe and the project deep_image_analogy.
Hope this is helpful.

![Adsız](https://user-images.githubusercontent.com/38671021/78021525-108bbc00-735c-11ea-80ea-380f0dca9094.png)

**Comment by hmmlillian** [comment]
@mfurkanns Have you tried to disable TDR (https://github.com/msracver/Deep-Exemplar-based-Colorization/issues/3#issuecomment-420507450)?

To disable TDR, you may change the TDR-related registry keys like this https://docs.microsoft.com/en-us/windows-hardware/drivers/display/tdr-registry-keys, or use NVIDIA Nsight Development Platform (https://docs.nvidia.com/gameworks/content/developertools/desktop/timeout_detection_recovery.htm) if you use NVIDIA GPU on Windows.

**Comment by mfurkanns** [comment]
Thank you for your help. It works for me.
